#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "164.125.68.221";
$SERVER_PORT = 15216;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
